### PR TITLE
Close completion widget when 'Esc' is pressed

### PR DESCRIPTION
**Pull request by llwu**
See Issue #601.

### CODE REVIEW

**Comment by jasongrout** [comment]
Thanks for pointing this out. Is there something in addition to #601, or is this a duplicate?

**Comment by llwu** [comment]
Sorry my bad, I meant issue #601. Amending commit and PR

**Comment by jasongrout** [comment]
Sorry, I didn't see this was a PR, not an issue. Thanks!

**Comment by jasongrout** [comment]
Looks good to me, works as advertised. Thanks!

**Pull request merged**
