### PR TITLE
Move command palette into app.

### PR DESCRIPTION
**Pull request by afshin**
This is one potential route we can take, offering the application's command palette instance as an attribute of `JupyterLab` instead of making it a plugin. But it's a fairly opinionated stance and has pros and cons.

Can we discuss this sometime before Friday?

cc: @sccolbert @ellisonbg @blink1073 @jasongrout

### CODE REVIEW

**Comment by afshin** [comment]
It feeds into a larger discussion of the least obtrusive way to handle dependency injection's semantics for users: the long list of arguments we currently pass might not be optimal.

**Comment by jasongrout** [comment]
What's the advantage of having the palette be a private (accessible) attribute instead of a plugin? Just one less argument for the DI framework?

My initial reaction is -1, since it would be harder to customize the palette and sets that particular ui component apart from other components.

**Comment by afshin** [comment]
We are treating the command palette as a core part of the interface right now, with screenshots and documentation in the landing/about page. So we should probably change the language used to describe it in the about page to indicate that even though it's part of the "default" build of JupyterLab, it's still a plugin and can be extended, *etc.*

landing plugin

But aside from that, I don't have any issue with it being a plugin. It was an attribute before the mono-repo. With the current `master`, post-mono-repo, it is a plugin. In this PR, it's an attribute again, but we could leave it as a plugin.

**Comment by blink1073** [comment]
Based on further discussion, we decided that it should continue to reside as a separate plugin, since there is nothing fundamentally different between this and the top level menu, and we have to draw the line somewhere, so we say that the app only contains the attributes defined in the base class.

**Pull request closed without merging**
