### PR TITLE
Fix race condition when adding a cell to an empty notebook model

### LINKED ISSUE #652: Unable to execute first cell
Hi,

We're trying to use JupyterLab to connect to an existing jupyter server. We see that the first cell doesn't execute, but if we add a new cell, that does execute. Upon looking at some of the objects in the Javascript console, we see that the model for the first cell has its `isDisposed` method returning True. The error manifests itself in the console as:
```
TypeError: write is not a function(…)
at MetadataCursor.setValue (http://localhost:34567/node_modules/jupyterlab/bundle.js?v=local:11809:10)
    at CodeCellWidget.set [as trusted] (http://localhost:34567/node_modules/jupyterlab/bundle.js?v=local:17130:34)
    at CodeCellWidget.execute (http://localhost:34567/node_modules/jupyterlab/bundle.js?v=local:17316:23)
    at Object.runCell (http://localhost:34567/node_modules/jupyterlab/bundle.js?v=local:2862:35)
    at run (http://localhost:34567/node_modules/jupyterlab/bundle.js?v=local:2353:36)
    at Object.runAndAdvance (http://localhost:34567/node_modules/jupyterlab/bundle.js?v=local:2385:17)
    at runAdvanceHandler (http://localhost:34567/node_modules/jupyterlab/bundle.js?v=local:197:45)
    at safeInvoke (http://localhost:34567/node_modules/jupyterlab/bundle.js?v=local:56559:26)
    at KeymapManager.processKeydownEvent (http://localhost:34567/node_modules/jupyterlab/bundle.js?v=local:56348:14)
    at HTMLDocument.<anonymous> (http://localhost:34567/node_modules/jupyterlab/bundle.js?v=local:124:25)safeInvoke @ bundle.js?  v=local:56562KeymapManager.processKeydownEvent @ bundle.js?v=local:56348(anonymous function) @ bundle.js?v=local:124
```

We see that the metadatacursor for the cell has _read and write as null:
```
MetadataCursor {_name: "trusted", _read: null, _write: null}
_name: "trusted"
_read: null
_write: null
name: "trusted"
```

The CodeCellModel for that first cell is disposed of even before the websocket connection is made, but it's never replaced with a new CodeCellModel, so during `CodeCellWidget.prototype.execute`,  when doing `this.trusted = true;` the setter throws that `write is not a function`. I see that the model is being disposed of during the `NotebookModel.prototype._onCellsChanged` started by the `NotebookModel.prototype.fromJSON` function. I also see that a new cell (and CodeCellModel) is added to the NotebookModel during the `fromJSON` function when there's no cells, and that this new model is not disposed...

So I guess my question is why the first cell is still using the old CodeCellModel that was already disposed of?

Thanks!

cc. @afshin

### PR DESCRIPTION
**Pull request by blink1073**
Fixes #652.

I used `requestAnimationFrame` because having at least one cell is a user-facing issue and not programmatically required.

### CODE REVIEW

**Comment by ellisonbg** [comment]
@aggFTW can you try this PR to confirm it addresses your issue?

**Comment by jasongrout** [comment]
The code looks good to me. We'll have to be careful about these issues going forward.

**Comment by jasongrout** [comment]
It might make sense to build an easy way in Phosphor to know if a signal is being recursively triggered. @sccolbert? In this situation, we ran into a problem when we triggered a signal inside the signal handler for that signal, so the inner signal came to previous handlers after and subsequent handlers before the outer signal did (even though it was temporally triggered later).

**Comment by jasongrout** [comment]
I replicated @aggFTW's issue (replacing the examples/notebook nb with the one they provided) based on their instructions in #652, and confirmed that this fixed the issue. @aggFTW - please let us know if you still are having issues with this.

**Comment by aggFTW** [comment]
Thanks for the work @jasongrout and @blink1073!
Verified and it works now.

Would another valid approach have been to not add a cell if empty inside the _onCellsChanged method and simply check at the very end of deleteCell and at the end of fromJSON?

**Comment by blink1073** [comment]
We don't necessarily know the source of the change, cutting all of the cells would have the same effect.

**Comment by aggFTW** [comment]
I see... Thanks!

**Comment by jasongrout** [comment]
hmmm...so cutting all the cells and immediately pasting them will also introduce an extra cell? That's a bit weird, but I guess it's what we can easily support now.

**Pull request merged**
