### PR TITLE
Fix contents regressions

### PR DESCRIPTION
**Pull request by blink1073**
cc @willingc, we also were not pulling in the file content anymore ;).

### CODE REVIEW

**Comment by willingc** [comment]
@blink1073 Thanks. After it passes Travis, I'll give it a look locally.

**Comment by willingc** [comment]
Looks good. Running locally, file content is now being pulled in and filebrowser updating. I'm assuming the "cancel" change/fix will be in a future PR.

**Comment by blink1073** [comment]
That is correct.

**Comment by willingc** [comment]
:shipit:

**Pull request merged**
