### PR TITLE
Fixed command-palette styling

### PR DESCRIPTION
**Pull request by spoorthyv**
Fixed the styling for the command-palette to how it was post scipy (+ the new search bar)

### CODE REVIEW

**Comment by spoorthyv** [comment]
This is how it looks like now.
screen shot 2016-08-22 at 3 47 50 pm

**Comment by blink1073** [comment]
@spoorthyv, sorry, looks like we picked up a merge conflict.

**Comment by blink1073** [comment]
(most likely the file was renamed to `.less` extension).

**Comment by spoorthyv** [comment]
Should I wait till all the less stuff is done? There seems to be a lot of css changes going on right now.

**Comment by blink1073** [comment]
I'd say yes.

**Comment by ellisonbg** [comment]
@spoorthyv If you rebase this now I can merge this...

**Comment by spoorthyv** [comment]
@ellisonbg look at #784. That should be ready to be merged.

**Comment by ellisonbg** [comment]
Closing this one...

**Pull request closed without merging**
