### PR TITLE
Refactor CSS location and order

### PR DESCRIPTION
**Pull request by blink1073**
- Renames `index.css` -> `base.css` in source directories.
- Moves `theme.css` -> `default-theme/foo.css`
- Ensures proper order of CSS
- Removes the extra `.p-Widget` tag that we needed because we could not be sure of the CSS import order

cc @ellisonbg, @jasongrout 

This does not *yet* address any CSS regressions explicitly.

cf #680 #586

### CODE REVIEW

**Comment by ellisonbg** [comment]
Great, I will play with this shortly. This is the approach that I am in favor of. We will probably have to follow this with another PR(s) that move things between the base/theme CSS - I am sure we have styles in one that belongs in the other. One thing that will help is to make a decision about what our UI should look like with no theme. My call would be everything that without a theme the UI should be as such:

* Everything functional and the right size (width, height, padding, margins)
* Light theme with black and white only - maybe a few greys where needed
* Borders in all the right places, with zero border radius
* Typography - simpletypeface, black on white, right size, no fancy style (small caps, bold, etc.)

To get this, we should (eventually in another PR) comment out the default theme and move things over to base.css and edit them until it all looks OK. Then enable the theme and edit until it looks final.

**Comment by ellisonbg** [comment]
Reviewing now"

* The csvwidget still has a `theme.css`

Other than that, looks good. I think we should merge this soon after you move the csvwidget theme file so other CSS work can continue.

**Comment by blink1073** [comment]
Done.

**Comment by ellisonbg** [comment]
Great, tests passing again, merging!

**Pull request merged**
