### PR TITLE
Add a main menu plugin

### PR DESCRIPTION
**Pull request by blink1073**
screen shot 2016-06-30 at 7 34 14 am

Intended to be used as:

```typescript
const plugin = {
  id: 'my-plugin',
  requires: [MainMenu],
  activate: (app: Application, menu: MainMenu) => {
    let myItem = new MenuItem({
      text: 'foo'
    });
    menu.addItem(myItem, { rank: 10 });
  }
};
```

### CODE REVIEW

**Comment by eskirk** [comment]
Shweet looks great. So I can make and add my own menu items to this? Could this also be used in conjunction with #196?

**Comment by blink1073** [comment]
Yes and yes ;).

**Comment by ellisonbg** [comment]
Awesome! A question:

Most of the time plugins will have commands they want to trigger based on the menu items. What is the API or recommended way of integrating menus and commands here?

**Comment by eskirk** [comment]
screen shot 2016-06-30 at 2 01 00 pm

Am I supposed to enable it somewhere using the code snippet you provided?

**Comment by ellisonbg** [comment]
Also, let's add a div to the left of the actual menus to put a small jupyter icon (similar to the design mockups that @cameronoelsen did).

**Comment by sccolbert** [comment]
@ellisonbg Menus, commands, and command palette are all automatically integrated once we switch to the new phosphor mono-repo.

**Comment by sccolbert** [comment]
You can also add icons to the menu items in the menu bar. I would suggest putting the jupyter icon in the first menu item, that way it actually does something when you click on it.

**Comment by blink1073** [comment]
@eskirk, the menu is there but empty until we start adding stuff to it using something like the code snippet in the top level comment in this thread.

**Comment by ellisonbg** [comment]
Needs a rebase...

**Comment by blink1073** [comment]
Rebased.

**Comment by ellisonbg** [comment]
Great, merging...

**Pull request merged**
