### PR TITLE
Update to Typescript 2.0 RC

### PR DESCRIPTION
**Pull request by jasongrout**
Hopefully the real release happens soon.

Interestingly, there were some errors in our code that the new typing features caught.

### CODE REVIEW

**Comment by jasongrout** [comment]
There is an issue still with https://github.com/jupyter/jupyterlab/blob/master/src/terminal/index.ts#L72. We have an ES2015 import, which means that the attribute is assumed to be read only. But we try setting it, which throws an error. I'm not sure yet what to do about it.

**Comment by jasongrout** [comment]
hehe... @blink1073 and @sccolbert - a lot of these checks are now compile-time errors:

```typescript
it('should be read-only', () => {
        let monitor = new ActivityMonitor<TestObject, number>({ signal });
        expect(() => { monitor.isDisposed = false; }).to.throwError();
      });
```

> Left-hand side of assignment expression cannot be a constant or a read-only property.

**Comment by jasongrout** [comment]
In the weekly dev meeting, we decided to hold off updating until 2.0 final comes out.

**Comment by jasongrout** [comment]
2.0 is [out](https://blogs.msdn.microsoft.com/typescript/2016/09/22/announcing-typescript-2-0/)! Continuing the update...

**Comment by blink1073** [comment]
Excelsior!

**Pull request merged**
