### PR TITLE
Implement input request handling

### LINKED ISSUE #495: Handle interactive kernel responses in output area
Executing inputs that don't immediately return a result (like invoking the help() functionality) require the output area to support handling input_request messages.

This is a general problem for both the notebook and the console. In order to see the problem manifest, at a console prompt, entering and executing the command help() will cause the kernel to pause while it waits for user input. The kernel will remain unusable from that point forward.

migrated from https://github.com/jupyter-attic/jupyter-js-notebook/issues/227

### PR DESCRIPTION
**Pull request by blink1073**
Fixes #495.   I'm going to hold of off writing more tests that involve the mock kernel for now, so tests will have to wait.

screen shot 2016-07-22 at 9 46 24 am

input_request

screen shot 2016-07-22 at 9 58 19 am

Latest with padding added after the prompt:
screen shot 2016-07-22 at 2 12 42 pm

### CODE REVIEW

**Comment by afshin** [comment]
Looks good. This is awesome.

**Comment by jasongrout** [comment]
AWESOME! I've wanted this for a while.

I'll have to figure out how to deal with this in the output widget. Right now I ignore it...

**Comment by blink1073** [comment]
This is ready.

**Comment by afshin** [comment]
Thanks!

**Pull request merged**
