### PR TITLE
Added FAQ page

### PR DESCRIPTION
**Pull request by spoorthyv**
Implemented the new FAQ page. Let me know if you have any ideas for more content.

### CODE REVIEW

**Comment by blink1073** [comment]
Can you make the folder name all lower case?

**Comment by willingc** [comment]
Looks good @spoorthyv and team. Question for you and @blink1073 (though don't let it hold up the PR): when the user clicks the link in the last FAQ response the link redirects you away from JupyterLab. Perhaps it would make more sense to open the "install kernel" documentation in a new browser tab?

**Comment by spoorthyv** [comment]
@blink1073 Made the change!

**Comment by willingc** [comment]
@spoorthyv I think that there may be some references in the file contents that still have FAQ and that may be causing Travis to complain. ``jupyterlab/index.js``

**Comment by spoorthyv** [comment]
Should work now. Also made few other minor changes.

**Comment by willingc** [comment]
Hmm... Travis is tripping over a jquery error https://travis-ci.org/jupyter/jupyterlab/builds/143399277

**Comment by blink1073** [comment]
@spoorthyv, you'll need to make the following changes:

```diff
diff --git a/examples/lab/index.html b/examples/lab/index.html
index 7b25599..026b171 100644
--- a/examples/lab/index.html
+++ b/examples/lab/index.html
@@ -5,6 +5,8 @@
   <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
   <link href="index.css" rel="stylesheet">
   <script type="text/javascript" src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_CHTML-full,Safe&amp;delayStartupUntil=configured"></script>
+  <script   src="https://code.jquery.com/jquery-3.1.0.min.js"   integrity="sha256-cCueBR6CsyA4/9szpPfrX3s49M9vUU5BgtiJj06wt/s="   crossorigin="anonymous"></script>
+  <script   src="https://code.jquery.com/ui/1.12.0/jquery-ui.min.js"   integrity="sha256-eGE6blurk5sHj+rmkfsGYeKyZx3M4bG+ZlFyA7Kns7E="   crossorigin="anonymous"></script>
   <script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.2.0/require.js"></script>
 </head>
 <body>
diff --git a/examples/lab/webpack.conf.js b/examples/lab/webpack.conf.js
index bbb201d..d5e6983 100644
--- a/examples/lab/webpack.conf.js
+++ b/examples/lab/webpack.conf.js
@@ -16,9 +16,19 @@ module.exports = {
     loaders: [
       { test: /\.css$/, loader: 'style-loader!css-loader' },
       { test: /\.json$/, loader: 'json-loader' },
-      { test: /\.html$/, loader: 'file' },
-      // Handle image
-      { test: /\.(jpg|png|gif|svg)$/, loader: "file" },
+      { test: /\.html$/, loader: 'file'},
+      // jquery-ui loads some images
+      { test: /\.(jpg|png|gif)$/, loader: "file" },
+      // required to load font-awesome
+      { test: /\.woff2(\?v=\d+\.\d+\.\d+)?$/, loader: "url?limit=10000&minetype=application/font-woff" },
+      { test: /\.woff(\?v=\d+\.\d+\.\d+)?$/, loader: "url?limit=10000&minetype=application/font-woff" },
+      { test: /\.ttf(\?v=\d+\.\d+\.\d+)?$/, loader: "url?limit=10000&minetype=application/octet-stream" },
+      { test: /\.eot(\?v=\d+\.\d+\.\d+)?$/, loader: "file" },
+      { test: /\.svg(\?v=\d+\.\d+\.\d+)?$/, loader: "url?limit=10000&minetype=image/svg+xml" }
     ]
+  },
+  externals: {
+    jquery: '$',
+    'jquery-ui': '$'
   }
 }
```

**Comment by blink1073** [comment]
Please run `npm install --save-dev url-loader` from the `examples/lab/` directory.

**Comment by blink1073** [comment]
Sorry @spoorthyv, looks like we picked up some conflicts.

**Comment by charnpreetsingh185** [comment]
@blink1073 should be good now!

**Comment by blink1073** [comment]
Looks good, well done!

**Comment by willingc** [comment]
Great job!

**Pull request merged**
