### PR TITLE
Updated logos to fit new brand guidelines

### PR DESCRIPTION
**Pull request by spoorthyv**
Made minor changes to all images in jupyterlab that I found that used our logo so that they are using the correct logo in correspondence with the new brand guidelines.

### CODE REVIEW

**Comment by afshin** [comment]
@spoorthyv The notebook icon now is proportioned differently to the text editor logo:

screen shot 2016-09-19 at 2 11 30 pm

Could you please re-save and confirm the places where these graphics appear (*i.e.*, the launcher and about page) have the correct sizes?

Thank you!

**Comment by ellisonbg** [comment]
@spoorthyv can you address the review comment?

**Comment by spoorthyv** [comment]
Yeah. I'm working on fixing it this right now.

**Comment by spoorthyv** [comment]
Ok, it should look good now!

**Comment by afshin** [comment]
Thanks @spoorthyv!

👍

**Pull request merged**
