### PR TITLE
More CSS Cleanup

### PR DESCRIPTION
**Pull request by blink1073**
- Audit Phosphor CSS for renames and restructure.
- Match existing theme.

screen shot 2016-08-19 at 4 15 47 pm

### CODE REVIEW

**Comment by blink1073** [comment]
I'm off for the day (I got an early start).

Still needs Sidebar love.
Notebook cell codemirror padding is wrong.
Also an overall once-over.

**Comment by ellisonbg** [comment]
Awesome, I will review this in the meantime. Many thanks!

**Comment by ellisonbg** [comment]
Just tried it out - going to wait until this is further along to do detailed review

**Comment by blink1073** [comment]
Still need to tweak the tabs, since we don't have a tab footer anymore.

**Comment by blink1073** [comment]
Done.

**Comment by ellisonbg** [comment]
Visually things are much improved. Still lots of small things ot fix, but at least the main layout is good. Options:

1) Merge at this point and keep improving/fixing things
2) Longer review of this PR - I can try to find everything and report it

I probably prefer 1 as many of the things I will end up fixing during finding them...

**Comment by jasongrout** [comment]
+1 for rapid iteration and progression.

**Pull request merged**
