### PR TITLE
Minor style improvement to notebook toolbar

### PR DESCRIPTION
**Pull request by ellisonbg**
* Removed double border at top
* Cleanup of CSS classes and styles
* 13px everything, right color
* Center vertically using line-height

screen shot 2016-06-09 at 5 47 00 pm

### CODE REVIEW

**Comment by ellisonbg** [comment]
Here is the before style:

screen shot 2016-06-09 at 5 49 46 pm

**Comment by SylvainCorlay** [comment]
@ellisonbg fontawesome is pixel perfect at 14px.

**Comment by SylvainCorlay** [comment]
So I think we should use multiple of that size for the toolbar icons and everywhere else.

**Comment by ellisonbg** [comment]
* Cameron and I did a design review of the typography in jupyterlab yesterday. We decided to use 13px as the main UI font size and 14px as the main user content font size.
* Cameron has designed custom button icons for everything (nicer than FA), so we won't be using FA much longer.

**Comment by SylvainCorlay** [comment]
Pixel perfection is important if you want to have crisp icons (unlike what we have now). Especially when the font-rendering engine is not the one of the latest osx with a retina display.

A lot of the choices in FA are driven by pixel perfection, (and not just to be nicer). Besides, google material icons are pixel perfect at the same size as Font Awesome.

**Comment by ellisonbg** [comment]
Here is 14px zoomed in:

screen shot 2016-06-09 at 6 21 01 pm

**Comment by ellisonbg** [comment]
14px and 13px compared

screen shot 2016-06-09 at 6 25 22 pm

**Comment by ellisonbg** [comment]
Talked to @SylvainCorlay - we are merging now and going to investigate using 14px for FA icons to get px perfect designs.

**Comment by SylvainCorlay** [comment]
Regarding pixel perfection, here are the promised screenshots on a screen that is not a retina: (cc @cameronoelsen)

13px:


14px:


Now, zoomed-in versions:

13px
13-large

14px
14-large

The latter is pixel perfect and much more crisp, and we can already see the difference in the original size. It become even clearer with the older font rendering engines of windows which does all kinds of ugly font hinting which cannot be disabled.

**Comment by SylvainCorlay** [comment]
@cameronoelsen when designing new icons to be used with fonts, designing glyphs on a grid that is the same one for *all* the icons of your font is important.

I have been using fontforge for the spyder icons, and it works pretty well even if the interface is quite old.

**Comment by SylvainCorlay** [comment]
Opening a new issue, actually.

**Comment by SylvainCorlay** [comment]
@ellisonbg here is the Spyder 3 icon theme which is an extension of Font Awesome:

spyder

Icons having multiple colors are stacks of monochrome font-based icons (like for the Python icon).

**Pull request merged**
