### PR TITLE
Restoring menu to correct font size

### PR DESCRIPTION
**Pull request by rnetro**

### CODE REVIEW

**Comment by blink1073** [comment]
Restoring...

**Comment by rnetro** [comment]
thanks!

**Comment by jasongrout** [comment]
Just noting this may have negative effects if we include 14px icons in here (but it doesn't appear the class is being used anywhere yet)

**Comment by rnetro** [comment]
Okay, 
My team’s current assignment is to match lab formatting to the notebook, so that’s why I kept it at 14px.
What size do you think would work?

Reese

**Comment by jasongrout** [comment]
> so that’s why I kept it at 14px.

It appears to have changed to 13px. Is that what you intended?

**Comment by rnetro** [comment]
Sorry for the confusion, yes the size is restored to what it was originally, 13px.
(correcting for this typo commit: https://github.com/jupyter/jupyterlab/pull/90/commits/da39f59c39a144e7364d26e12a294e5a1a605662 <https://github.com/jupyter/jupyterlab/pull/90/commits/da39f59c39a144e7364d26e12a294e5a1a605662>)
thanks :)

**Pull request merged**
