### PR TITLE
[Inactive] Design Changes to Help Plugin

### PR DESCRIPTION
**Pull request by charnpreetsingh185**
This is the initial PR for Design changes to the help plugin. I have included screenshots of the updates. 

screen shot 2016-06-29 at 9 47 35 am
screen shot 2016-06-29 at 9 48 09 am
screen shot 2016-06-29 at 9 48 22 am

### CODE REVIEW

**Comment by sccolbert** [comment]
The help plugin runs the widget in the side bar area (as opposed to main area) because `<iframe>` elements steal mouse events. This means that drag-drop breaks when trying to drag a tab over the `<iframe>`.

**Comment by charnpreetsingh185** [comment]
> drag-drop breaks when trying to drag a tab over the `<iframe>`

@sccolbert   I'm not sure what you mean by that. Could you please elaborate on that? I tried it on my end and it works.

**Comment by sccolbert** [comment]
@charnpreetsingh185 configure the page as you have in the last image, with the `<iframe>` displaying the scipy docs. Then, try to drag-and-drop a file from the file browser over that the iframe. The iframe will eat the mouse events, which will prevent the drag-and-drop action from working properly. 

This is a fundamental limitation with iframes. There's a workaround, but it's expensive. We (the project) haven't yet fully decided how to handle iframes in a way which doesn't suck. So the current rule is "no iframes in the main area".

**Comment by charnpreetsingh185** [comment]
@sccolbert  Thanks for the explanation. I tried what you are describing and still can't see where it is breaking. 
testing

**Comment by sccolbert** [comment]
Ah. Ok. We've already set up the expensive workaround:
https://github.com/jupyter/jupyterlab/blob/master/src/default-theme/help.css#L26-L34

Basically, whenever a drag starts, we overlay a transparent div over the iframe and disable pointer events for that div. It works, but it's expensive.

The second (less immediately important) problem with iframe is that they reload whenever their position in the DOM tree changes. You can see this in your most recent gif when you drop the new item.

**Comment by ellisonbg** [comment]
Hi @sccolbert the folks who submitted are one of the student teams here at Cal Poly. Looking at this now with them. I know iframes are a total pain, but they are trying to understand what exactly won't work. Also worried that if the limitations exist we will still run into them evetually with iframes in the L/R panel.

**Comment by ellisonbg** [comment]
Ahh, thanks for the clarification...

**Comment by jasongrout** [comment]
If this is going inactive, it's probably best to close the PR to clear out the PR queue. We can always either open it back up, or get the branch and create a new PR.

**Comment by sccolbert** [comment]
Was it decided in the call I missed that this is going inactive?

**Comment by charnpreetsingh185** [comment]
Yes, due to the `iframe` issue, we decided to go back to the original Help plugin design.

**Comment by sccolbert** [comment]
Ok. Thanks!

**Comment by sccolbert** [comment]
I agree with @jasongrout about the closure.

**Pull request closed without merging**
