### PR TITLE
Update npm and python setup

### LINKED ISSUE #20: tsc dev dependency missing
You guys probably have it globally installed.

### PR DESCRIPTION
**Pull request by jasongrout**
Introduced the top-level `nom run build:serverextension` command and cleaned up the python setup.py script to use it.

Fixes #20

### CODE REVIEW

**Comment by jasongrout** [comment]
@SylvainCorlay - does this solve your issue?

**Comment by jasongrout** [comment]
@fperez - I added the git hooks here too.

**Comment by blink1073** [comment]
@jasongrout, I added a PR against your PR to provide a `watch:serverextension` script.

**Comment by jasongrout** [comment]
Thanks! I was hoping there would be a watch eventually...

**Comment by jasongrout** [comment]
This also fixes #27.

**Comment by blink1073** [comment]
In it goes...

**Pull request merged**
