### PR TITLE
Styling file drag (matching selected/non-selected)

### PR DESCRIPTION
**Pull request by rnetro**
screen shot 2016-07-12 at 5 00 00 pm

### CODE REVIEW

**Comment by sccolbert** [comment]
Can you add a transform to the drag image so that the cursor is better positioned during the drag?

https://github.com/phosphorjs/phosphor-dockpanel/blob/master/example/index.css#L161

**Comment by sccolbert** [comment]
@rnetro I added a WIP tag pending the transform for the drag image.

**Comment by rnetro** [comment]
Thanks, I'm working on it right now (having a smidge of git trouble, haha)

**Comment by rnetro** [comment]
@sccolbert ...repositioned!
screen shot 2016-07-13 at 4 22 13 pm

**Comment by sccolbert** [comment]
Woah, something happened to this PR. It's now 44 changed files. Maybe needs a rebase against master?

**Comment by rnetro** [comment]
Geez okay, will do

**Comment by rnetro** [comment]
this is weird... I think I'm going to open a new branch...

**Pull request closed without merging**
