### PR TITLE
Less is more

### PR DESCRIPTION
**Pull request by ellisonbg**
Starting to work on adopting less. This isn't the final word on our usage of CSS preprocessors, just a step along the way. I will post design notes below as I get further along...

### CODE REVIEW

**Comment by ellisonbg** [comment]
OK this is ready. Here is an overview:

* Created a new basestyle folder that has global base less, global base less variables and a base index.less that gets compiled into a index.min.css
* Converted all existing files to less
* The index.css in default-theme is now index.less and gets compiled into index.min.css
* The index.css from basestyle and default-theme are both required in jupyterlab/index.js in the right order.
* Added all needed build commands in package.json

There is a ton more to do in refactoring the css to use the features of less. But I want to merge this quickly and iterate in further PRs as this touches *every* css file in the repo and will quickly conflict with other PRs.

**Comment by ellisonbg** [comment]
I also want to emphasize that there are a ton of questions related to exactly how we want to use a CSS preprocessor. Some of those questions:

* Server-side or client-side
* How to propagate theme variables to third party plugins and get them to render
* Which preprocessor
* Where exactly to put all the files.

My plan is to explore these things slowly using less, while giving devs/designers a more solid foundation to use today (using less for now).

**Comment by ellisonbg** [comment]
Hmm, build is failing on Travis because of this:

```
ERROR in ./build/index.js
Module not found: Error: Cannot resolve module 'jupyterlab/lib/default-theme/index.css' in /home/travis/build/jupyter/jupyterlab/examples/console/build
 @ ./build/index.js 14:0-49
```

But I don't require index.css I require index.min.css

**Comment by ellisonbg** [comment]
Found it, I hadn't fixed the examples yet.

**Comment by ellisonbg** [comment]
Merge this before #706

**Comment by afshin** [comment]
Great, thanks @ellisonbg!

**Comment by SylvainCorlay** [comment]
> Server-side or client-side

@ellisonbg one thing that we have been doing for some time in bqplot is load the some variables from the notebook less files that were served by the server, even though they were statically compiled.

bqplot's less was compiled in-browser.

So even in the case of a server-side compilation, exposing some `less` files with variables to be used can be useful.

**Comment by SylvainCorlay** [comment]
Has it been decided that we would go for `less` instead of `myth`?

**Pull request merged**
