### PR TITLE
Clear signal data when disposing of the observableundoablelist

### LINKED ISSUE #58: Testing shows an error message "Exception in signal handler"
I see two errors when doing `npm run test` on 4e59585dfdc334286bb3fbc1b4ffd6c702c8a4d2 `ERROR: 'Exception in signal handler:', TypeError{}`. I see these when I run the tests manually under chrome and firefox. I see them on various Travis runs too.

### PR DESCRIPTION
**Pull request by blink1073**
Fixes #58.

### CODE REVIEW

**Comment by sccolbert** [comment]
lgtm - you may want to also declare `implements IDisposable` for the class signature.

**Comment by blink1073** [comment]
Are we moving `observablelist` into this repo?  If so, I can move it now and make it disposable.

**Comment by sccolbert** [comment]
:+1:

**Comment by sccolbert** [comment]
Can probably clean it up too. Lot's of shennanigans were done to the original in order to make it subclassable. You probably don't need any of that. We can also make it an `ISequence` to work with the new phosphor algorithms and such.

**Comment by blink1073** [comment]
Okay, I'll wait until we switch to the new `phosphor` then to absorb it.

**Comment by sccolbert** [comment]
:shipit: once Travis passes

**Comment by jasongrout** [comment]
ObservableList is being evicted from phosphor?

**Comment by sccolbert** [comment]
For the time being. We ended up having no use for it ourselves. And it would make little sense for me to maintain a one-off observable collection.

**Pull request merged**
