### PR TITLE
Revert "Clean up the jupyterlab extension package"

### PR DESCRIPTION
**Pull request by afshin**
Reverts jupyter/jupyterlab#584

### CODE REVIEW

**Comment by afshin** [comment]
This PR ends up breaking the `pip install`. For the time being, because the mono-repo migration is first priority, I'm just reverting it. It may be a very simple fix.

In the future, we may want to upgrade the Travis scripts to include the `pip install -e .` step to catch build esoteric errors.

cc: @blink1073

**Comment by blink1073** [comment]
Booo, building is hard...

**Comment by blink1073** [comment]
:+1: for merge

**Comment by afshin** [comment]
Cheers! Get back to not being here.

**Pull request merged**
