### PR TITLE
Update MathJax config to mirror notebook.

### LINKED ISSUE #590: Locally build jupyter lab fails to load STIX files
I've build jupyter lab locally from master like described in the readme.

After starting and opening an .md file with "Open with -> Rendered Markdown" I noticed a 404 error in the console for the following URL:  
http://localhost:8888/static/components/MathJax/jax/output/HTML-CSS/fonts/STIX/fontdata.js?rev=2.6.0 

On my conda installation the files are in:
~/miniconda3/lib/python3.5/site-packages/notebook/static/components/MathJax/jax/output/HTML-CSS/fonts/__STIX-Web__/ 
.. and not  in
~/miniconda3/lib/python3.5/site-packages/notebook/static/components/MathJax/jax/output/HTML-CSS/fonts/__STIX__/ 

Am I missing some extra dependencies or is that just a bug in jupyter?

### PR DESCRIPTION
**Pull request by jasongrout**
Fixes #590

### CODE REVIEW

**Comment by jasongrout** [comment]
As a bonus, this fixes mathjax to actually work too!

**Comment by blink1073** [comment]
I'm getting this when running against Notebook v4.2.2 because it does not ship `CommonHTML`:

http://localhost:8888/static/components/MathJax/jax/output/CommonHTML/fonts/TeX/fontdata.js?rev=2.6.0 Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by blink1073** [comment]
Never mind, it does have it, investigating.

**Comment by blink1073** [comment]
Oh, it has `CommonHTML` but no `fonts` folder.

**Comment by blink1073** [comment]
Weird, I have the same issue when running `jupyter notebook`.

**Comment by blink1073** [comment]
Wow, switching to incognito mode with no changes to this PR works for me.  I tried clearing all browser data, but the problem persists outside of incognito mode.

**Comment by blink1073** [comment]
Sanity restored by resetting my Chrome settings (works here and the classic notebook now).

**Comment by blink1073** [comment]
Thanks!

**Comment by jasongrout** [comment]
You may have specifically selected in MathJax (right-clicking on an expression) that you use CommonHTML at one point, which then is a remembered setting. By default in the notebook, we still use HTML-CSS.

**Comment by jasongrout** [comment]
We eventually want to switch to CommonHTML, I think. See https://github.com/jupyter/notebook/pull/1032#issuecomment-178441275.

**Pull request merged**
