### PR TITLE
Make line wrapping, numbers, and matching brackets per-editor settings.

### PR DESCRIPTION
**Pull request by jasongrout**
It's really frustrating having line wrapping a global setting when you trying to edit different files.

### CODE REVIEW

**Comment by jasongrout** [comment]
This doesn't *quite* solve all the issues, because it doesn't check to see if an editor currently has focus. So if you are working in an editor, and the switch to lots of other activities, the toggle applies to the last focused editor. I think it should be a no-op unless you are actually focused on an editor.

**Comment by blink1073** [comment]
Why not have all/current versions of all these things?  The palette can handle it ;).

**Comment by jasongrout** [comment]
Yes, fair enough. Let's make it a different ticket.

**Comment by jasongrout** [comment]
That would be quite a proliferation. I think the most common use-case is per-buffer settings for these. I think settings should handle anything more than that. But let's discuss it on a different ticket.

* Toggle Line numbers
* Toggle Line wrapping
* Toggle Match brackets
* Line numbers on
* Line wrapping on
* Match brackets on
* Line numbers off
* Line wrapping off
* Match brackets off

**Comment by blink1073** [comment]
Fair enough.  This looks good, thanks!

**Comment by jasongrout** [comment]
Issue for implementing a settings system: #515

**Comment by jasongrout** [comment]
> This doesn't quite solve all the issues, because it doesn't check to see if an editor currently has focus. So if you are working in an editor, and the switch to lots of other activities, the toggle applies to the last focused editor. I think it should be a no-op unless you are actually focused on an editor.

This is #516.

**Comment by jasongrout** [comment]
By the way, I noticed this bug in Codemirror when changing matchBrackets on a per-editor basis, which Marijn just fixed: https://github.com/codemirror/CodeMirror/issues/4128

**Pull request merged**
