### PR TITLE
Third Party Extensions - Use AMD

### PR DESCRIPTION
**Pull request by blink1073**
cf #224.

Switches to create AMD shims and use AMD everywhere.

### CODE REVIEW

**Comment by blink1073** [comment]
This concept works as of 93e5441, but the modules still have to be explicitly loaded after the bundles they depend on have already been loaded. I tried playing with `bundles` and `deps` `RequireJS` config, but could not find the secret incantation.

**Comment by blink1073** [comment]
`bundles` assume that the file is a flat list of `defines()`, but ours is nested.  `deps` are loaded asynchronously and in parallel.

**Comment by blink1073** [comment]
We can't just `require` all of the bundles in order (un-nested), because they load in parallel.

**Comment by blink1073** [comment]
I think the solution is for the server to generate this bootstrapping code, we were going to have to do something similar with `script` tags anyway, but now we have the benefits of no global variables and having all of the modules available via AMD.

**Comment by jasongrout** [comment]
What do you think of the requirejs author's comments in "Past and Future" in the requirejs 2.2 release notes? http://jrburke.com/2016/03/17/requirejs-2.2-alameda-1.0-released/

**Comment by jasongrout** [comment]
In particular:
> If you do want to use loader that has a more modern, smaller codebase, try alameda. That is the codebase I would like to maintain for an AMD loader going forward, and where I would consider larger structural changes.
> ... I like the smaller, modern core of alameda. I look forward to using it if a project calls for an AMD loader, although I am happy to work on projects that would not require it.

**Comment by jasongrout** [comment]
> bundles assume that the file is a flat list of defines(), but ours is nested. deps are loaded asynchronously and in parallel.

What if we insert in the end of a bundle a require() call requiring that bundle, or change the top-level define to a require? Then the inner defines are run automatically.

**Comment by blink1073** [comment]
One of the reasons to *use* RequireJS was that it was stable and ubiquitous, I am wary of a switch to `alameda`.  I'd prefer to wait and switch to an ES7+ loader when the day comes.

**Comment by blink1073** [comment]
I'll keep digging on the auto-loading.

**Comment by jasongrout** [comment]
> One of the reasons to use RequireJS was that it was stable and ubiquitous, I am wary of a switch to alameda. I'd prefer to wait and switch to an ES7+ loader when the day comes.

Yes, that went through my mind too. It was nice that it always returned a promise for the module, which took care of one of the issues we were talking about.

**Comment by blink1073** [comment]
True, and he is committed to the same overall API, *and* it is a 1.0 release, *and* the other one is only supported in an LTS fashion...

**Comment by blink1073** [comment]
Changing from `define()` to `require()` did not work.  The outer `define()` for services looks like:

```javascript
define(["phosphor/lib/core/disposable.js","phosphor/lib/core/signaling.js"], function(__WEBPACK_EXTERNAL_MODULE_22__, __WEBPACK_EXTERNAL_MODULE_23__) {
```

We would need to wrap this whole thing in a `require(['phosphor'])` block *after* the WebPack bundle is generated.

**Comment by blink1073** [comment]
What I had hoped is to be able to define the dependencies of each module somehow, which is what I thought `bundles: { 'phosphor': ['phosphor/lib/core/disposable', .... }` would accomplish.

**Comment by blink1073** [comment]
`shim` only works on modules that are not AMD to begin with, so this does not work either:

```javascript
  shim: {
    'jupyter-js-services': {
      deps: 'phosphor.bundle'
    }
  }
```

**Comment by jasongrout** [comment]
> We would need to wrap this whole thing in a require(['phosphor']) block after the WebPack bundle is generated.

Not if we put, at the bottom of the phosphor bundle (or on the page after loading the phosphor bundle) `require('phosphor')`, which should define the phosphor paths individually, right?

**Comment by jasongrout** [comment]
Just curious, is it out of the question to use the requirejs optimizer?

**Comment by blink1073** [comment]
The `phosphor` `defines` are ready as soon as the `phosphor` bundle itself is loaded, so adding more config to it will not help.

The optimizer would not know where to look for `phosphor/lib/foo` either.

**Comment by blink1073** [comment]
We also can't run the optimizer on the user's machine, so that is a non-starter for handling downstream extensions.

**Comment by blink1073** [comment]
That means walking up the dependency tree and loading the bundles in reverse order.  
In the case of peer dependencies with compatible external library semvers, we would pick one and use `paths` config to map the other one.

**Comment by blink1073** [comment]
(i.e. recreate npm dedupe and package resolution).

**Comment by blink1073** [comment]
Closing in favor of a forthcoming self-contained approach.

**Comment by blink1073** [comment]
cf #728

**Pull request closed without merging**
