### PR TITLE
Adding design folder, with a file for the terminal.

### PR DESCRIPTION
**Pull request by ellisonbg**
Going to use files in this directory to guide student work on the different plugins.

### CODE REVIEW

**Comment by sccolbert** [comment]
Is this WIP or ready for review?

**Comment by ellisonbg** [comment]
Ready for review - my student teams will be completing more of this stuff
over the next few weeks as they dive into jupyterlab.

On Mon, Jun 20, 2016 at 1:50 PM, S. Chris Colbert <notifications@github.com>
wrote:

> Is this WIP or ready for review?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/jupyter/jupyterlab/pull/126#issuecomment-227303451>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AABr0LviwK8plOrfnJs2CqI1QceAfKNrks5qNydbgaJpZM4I6NzS>
> .
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by blink1073** [comment]
Looks fine to me.

**Comment by katiewhite360** [comment]
@blink1073 Is there any chance our intern team could get on quick call with you (10-15 minutes) sometime this week to ask a couple questions about jupyterlab?

**Comment by blink1073** [comment]
Sure, I am available for the next two hours or anytime tomorrow outside of the JupyterLab meeting (10am Pacific).

**Comment by katiewhite360** [comment]
Can we schedule a call for 12 pm tomorrow?

**Comment by blink1073** [comment]
12pm Pacific it is.

**Comment by katiewhite360** [comment]
Thanks, talk to you then!

**Comment by katiewhite360** [comment]
appear.in/katiewhite360

**Comment by blink1073** [comment]
We typically use `appear.in/jupyter` unless it needs to be private for some reason.

**Comment by katiewhite360** [comment]
That works! Let's do that then.

**Pull request merged**
