### PR TITLE
HTML table redesign

### PR DESCRIPTION
**Pull request by ellisonbg**
Here is an initial attempt to clean up the HTML table design.

* Better colors and font size
* Minimal borders
* Right align everything (can't distinguish text/numbers in pure CSS)
* Better padding
* Prevent wrapping text in cells and show ellipses in long cells

We may want to do zebra striping and get rid of the bold heading style? I can do variations with those options...

screen shot 2016-09-19 at 11 34 11 pm

screen shot 2016-09-19 at 11 34 27 pm

screen shot 2016-09-19 at 11 34 40 pm

### CODE REVIEW

**Comment by ellisonbg** [comment]
Fixes #904

**Comment by ellisonbg** [comment]
Here is a zebra striped version with no bold headings...

screen shot 2016-09-19 at 11 46 19 pm

**Comment by ellisonbg** [comment]
Also, not sure about centering tables in output. We don't do that for other things like images...

**Comment by rgbkrk** [comment]
Love it.

**Comment by fperez** [comment]
Looking great, though I'd hold back on the centering, for the reason you mention.  Consistency on these things is probably good to keep.

**Comment by kiwirob** [comment]
This looks great. Will it handle presentation of Pandas dataframes with MultiIndexes?

**Comment by hadley** [comment]
A big improvement! I definitely prefer the zebra striped version (although I think you should keep the bold headers).  A few other questions/comments:

1. Ideally `NaN` would get styled slightly differently.  That's particularly important for string column so you can distinguish missing values from the equivalent text.

1. The fertility column has varying decimal places. I think it's important to ensure that they're constant because then you can easily see the rough order of magnitude.  And what happens if you have a very wide range of number values, i.e. 123e10 – 123e-10? 

1.  It think it would be nice if you could make the row numbers somewhat less visually prominent. Maybe a light grey colour?

1. Can you show an example of a string column with embedded newlines?

1. For columns like pop you might want to consider adding commas every 3 digits.

**Comment by ellisonbg** [comment]
@hadley thanks for the feedback...

It is important to note that this style is used for all tables in JupyterLab and is pure CSS. Because of this:

* It should be looked at as the lowest common denominator for all tables, not just DataFrames.
* We can't do any styling in this CSS that is data aware. That doesn't prevent Pandas from adding extra data aware styling to handle NaNs, precision, left aligning strings, number formatting, etc. I will follow this PR up with opening issues on Pandas to address these other things.

On the lines, versus zebra stripes, I am torn. My current understanding of this area is zebra stripes likely don't make much of a difference in terms of the speed/accuracy which with users can read a table, but there is a slight aesthetic preference among users to have them. On the other side Tufte opposes them as chart junk. Some references:

http://www.edwardtufte.com/bboard/q-and-a-fetch-msg?msg_id=0001IV
http://alistapart.com/article/zebrastripingdoesithelp

**Comment by TomAugspurger** [comment]
@ellisonbg we can use https://github.com/pydata/pandas/issues/5562 for Hadley's points. I'll update that.

**Comment by ellisonbg** [comment]
I propose that @hadley and @edwardtufte arm wrestle to settle the zebra stripe versus no zebra stripe question...I am really on the fence on this one...

**Comment by hadley** [comment]
I propose a brownie bake off (http://www.jstor.org/stable/1940770?seq=1#page_scan_tab_contents)

**Comment by ellisonbg** [comment]
@TomAugspurger I think that pandas should use this style as it starting point and add additional data-aware inline styles to address the points that @hadley has brought up.

**Comment by ellisonbg** [comment]
Here is the version with zebra stripes, bold headings:

screen shot 2016-09-20 at 10 25 13 am

**Comment by minrk** [comment]
Awesome! I share a slight preference for zebra and bold headers.

**Comment by ellisonbg** [comment]
A follow up issue to left justify tables in output...

https://github.com/jupyter/jupyterlab/issues/913

**Comment by ellisonbg** [comment]
I could also do no fixed zebra stripes, but stripe the hovered row.

**Comment by sccolbert** [comment]
I prefer zebra stripes to hover styles.

**Comment by TomAugspurger** [comment]
There was a question about MultiIndexes:

screen shot 2016-09-20 at 9 46 59 am

(that could be a couple commits old)
In pandas these are implemented with `rowspan="3"`, which could be confusing the zebra-striping.

**Comment by ellisonbg** [comment]
If you have a depth 2 hierarchical row index, the zebra stripe style works well:

screen shot 2016-09-20 at 10 54 31 am

For more than depth 2, the style gets a bit weird. However, having the bottom borders will also face his same issue.

**Comment by TomAugspurger** [comment]
If necessary, pandas can add options to override the CSS. Like you said, this style should be a reasonable default for all tables, not just DataFrames.

**Comment by ellisonbg** [comment]
Here is the result of the Twitter poll:

screen shot 2016-09-20 at 3 49 33 pm

While I don't belieive in "design by Twitter poll" in general, this does support the sentiment from @hadley and @minrk here. I think we should call it Zebra for now...

**Comment by ivanov** [comment]
I like the way this looks, it seems there's a preference for it from the responses to the twitter poll. Going to merge it so we can roll with it.

zebra
zebranodding

**Comment by ngaloppo** [comment]
I highly recommend this: 
http://blog.darkhorseanalytics.com/clear-off-the-table

image

**Comment by sclarke** [comment]
Would it look less busy if the zebra stripes were wider /chucked? Striping two or three rows together might work well if CSS can do that.

**Comment by sjobeek** [comment]
One vote for the less-is-more camp

**Comment by jorisvandenbossche** [comment]
I really like the new styling (thanks for that!), but, one aspect of this change that I would find a bit annoying as a pandas user is the hardcoded maximum width of columns. In pandas long strings are already shortened in the html display (but maybe the default is too long for good taste), but if you really need to see the content of the column with long strings, you can set a display option for this with `pd.options.display.max_colwidth`. AFAIU, this will no longer work with this change. 
Small illustration: http://nbviewer.jupyter.org/gist/jorisvandenbossche/207b452cd724a872ca32d4b8138e0714

**Pull request merged**
