### PR TITLE
Remove unnecessary decoration

### LINKED ISSUE #153: Less chrome
Assuming that #147 gets merged, the dockarea will look like. It is already de-cluttered compared to the current version.

chrome

Still, the top-right square in every tab area is not very useful. We could remove it and get something visually less cluttered like this:

less-chrome

### PR DESCRIPTION
**Pull request by SylvainCorlay**
This implement the proposal of #153. (Closes #153).

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
Ubuntu + chrome screenshot
screenshot

**Comment by SylvainCorlay** [comment]
An example of Microsoft Blend, which uses similar type design *and* adds things in this area.

tbs

I like this better because it removes clutter from the interface.

**Comment by sccolbert** [comment]
This shouldn't be merged until there is consensus. The conversation in #153 is not done yet IMHO.

**Comment by SylvainCorlay** [comment]
Sure. I had the branch hanging around so here it is.

**Comment by jasongrout** [comment]
Brian just let us know on appear.in that the consensus now is in favor of this change.

**Pull request merged**
