### PR TITLE
Install splitpanel in base package

### PR DESCRIPTION
**Pull request by blink1073**
cf https://github.com/jupyter/jupyterlab/issues/524#issuecomment-234812491

### CODE REVIEW

**Comment by ellisonbg** [comment]
Cool merging!!!

**Comment by afshin** [comment]
@blink1073 my current state does not have this fix (haven't merged yet) but a totally clean build works for me. It appears that my `npm` (version `3.8.6`) is hoisting all the `phosphide` dependencies into peer ones so I end up having `phosphor-splitpanel`. Is this behavior different than what other `npm` versions do? The CI build appeared to be working and doing the same thing as well, I think.

**Comment by afshin** [comment]
*n.b.*, Obviously, this belongs in `package.json` like you've added, I just want to know why it doesn't break in some instances but does in others.

**Comment by blink1073** [comment]
Yep, older versions of npm did not do that.

**Pull request merged**
