### PR TITLE
Allow type ahead to work while long-running cells execute.

### PR DESCRIPTION
**Pull request by afshin**
Fixes https://github.com/jupyter/jupyterlab/issues/392
cc: @asmeurer

typeahead

### CODE REVIEW

**Comment by blink1073** [comment]
Hmm, it seems like we'd want to scroll into view whenever we type a character as well (for the notebook as well), since the position could change as output is added to previous cell(s).

**Comment by afshin** [comment]
@blink1073 @jasongrout
Output is added atomically, not incrementally, right? The promise handlers both scroll to the bottom when the execution result comes in. Is this insufficient?

**Comment by blink1073** [comment]
You can get more thank one output for a given execute request.

**Comment by afshin** [comment]
But the promise resolves only one time and after its resolution the widget sets its scroll position to the bottom. I think I'm missing something.

**Comment by blink1073** [comment]
The promise is fulfilled when we get the final execute_reply message, but other messages preceed it.

**Comment by blink1073** [comment]
We could: connect to the changed signal of the output model, or scrollintoviewifwefeellikeit on a textchanged signal.

**Comment by afshin** [comment]
I see, that makes sense. Checking to scroll on every text change seems really heavyweight to me. Is this avoidable? `scrollIfTheTimeIsRightAndThePlaceIsCloseEnoughToRight` isn't a call I want to make too frequently.

**Comment by blink1073** [comment]
In the console, you at least know when the previous cellis doing stuff.  It is less clear in the notebook where the changing cell could be 3 cells above.  Tricky....

**Comment by jasongrout** [comment]
It may be a moot point, because browsers typically already scroll so that input areas are visible. So it may be that every keystroke will cause the browser to focus. Let's test.

**Comment by jasongrout** [comment]
Yeah, every time you type a character, the browser scrolls anyway:

scrolling

So it sounds like it's automatically doing what @blink1073 suggested.

**Comment by afshin** [comment]
I wish I'd checked before venturing into a rabbit hole ... 😆

**Comment by jasongrout** [comment]
I've just had my head deep into scrolling and focusing issues the last 36 hours or so :)

**Pull request merged**
