### PR TITLE
Simplified font definitions

### PR DESCRIPTION
**Pull request by bliker**
I removed multiple definitions of the font and just replaced it with `sans-serif` in the body. Letting the browser decide the best sans serif font on the platform.

### CODE REVIEW

**Comment by bliker** [comment]
👍 Helveticas and Arials eliminated

**Comment by bliker** [comment]
Essentially the result of this will affect only very small percentage of users - only about 7% of users have helvetica on windows that now be replaced with Arial. Also linux users will have better optimised Liberation Sans.

**Comment by jasongrout** [comment]
We should probably have a time limit on discussion items/calls for comment like this to avoid bitrot and bikeshedding. How about 2 business days? One week?

**Comment by jasongrout** [comment]
CC @ellisonbg

**Comment by jasongrout** [comment]
(to clarify, a time limit on starting the discussion/waiting for comments before reviewing and merging, not a time limit on the resulting discussion, which could be decided as the discussion proceeds...)

**Comment by ellisonbg** [comment]
Sorry, I had forgot to follow the repo. I am fine with this change.

**Comment by blink1073** [comment]
Hi @bliker, sorry, this has a merge conflict.  Here are the commands used to rebase (assumes you've named `jupyter/jupyterlab` "upstream"):

```bash
$ git fetch upstream master
$ git rebase -i upstream/master
```

**Comment by bliker** [comment]
Should be OK now :)

**Comment by blink1073** [comment]
Thanks, rolling.

**Pull request merged**
