### PR TITLE
Scroll output and let output be selected

### LINKED ISSUE #471: Scroll left-right in notebook output
Sometimes notebook output will be too wide to fit within the size of the tab. For example, right now I've got a pandas dataframe with a bunch of columns with long names, and it's printing off the right edge of the notebook tab, which I currently have maximized within Jupyter Lab.

In Pineapple and the browser-based Jupyter Notebook editor, you can scroll left and right to view such horizontally-oversized output. Can the same be done in Jupyter Lab?

### PR DESCRIPTION
**Pull request by jasongrout**
Fixes #471 and provides a partial fix for #355.

### CODE REVIEW

**Comment by jasongrout** [comment]
CC @drussellmrichie - can you check to see if this does what you want on #471?

**Comment by drussellmrichie** [comment]
Sorry it's taken me a bit to respond to this. This is really the first time that I'm using github collaboratively/nontrivially, so I'm having to figure out (with a lot of help...!) to how fetch pr's, etc.

So, here's what I did:

```
cd jupyterlab
git remote add jasongrout https://github.com/jasongrout/jupyterlab.git
git fetch jasongrout
git checkout scrolloutput
```

The terminal output from all that looked good (and indeed, I could see that the index.css file you edited was changed appropriately), so I fired up Jupyter Lab in Chrome [Version 51.0.2704.106 (64-bit)]. Unfortunately, I'm not seeing any difference in behavior: I still can't scroll across superwide cell outputs nor can I select cell outputs.

But perhaps I'm doing something wrong....?

**Comment by jasongrout** [comment]
And then you'll probably want to start up a new incognito session to make sure you don't have any browser caching giving you old css.

**Comment by sccolbert** [comment]
@drussellmrichie I think you need `git checkout jasongrout/scrolloutput` to get his branch instead of your branch.

**Comment by drussellmrichie** [comment]
@sccolbert, `git checkout scrolloutput` seemed to work for me. It spat this out:

```
Branch scrolloutput set up to track remote branch scrolloutput from jasongrout.
Switched to a new branch 'scrolloutput'
```

Anyway, yes, @jasongrout was right that I had to re-run the npm commands (with the sudo and --unsafe-perms work-arounds that I had to do in #408). Then I did `pip install -e .` again (which was maybe redundant?), and finally booted up jupyter lab again.

And voila, now I have glorious, righteous cell output selection and scrolling (in both an incognito window and a regular Chrome window)!

You guys seriously rock.

**Comment by sccolbert** [comment]
hmmm, we still shouldnt need sudo for any of this, but that's another battle :)

glad you got it working

**Comment by jasongrout** [comment]
@drussellmrichie, in any unmerged pull request, you can get the command to checkout the PR by going to the bottom of the PR and clicking "view command line instructions.". It will open a window showing you the commands to check out the branch. That's what I do...

**Comment by jasongrout** [comment]
For PR 481, for example, I copy and paste this into my terminal: 
```
git checkout -b eskirk-menubar_normalization master
git pull https://github.com/eskirk/jupyterlab.git menubar_normalization
```

**Pull request merged**
