### PR TITLE
Fixes output areas to work well with @interact

### PR DESCRIPTION
**Pull request by jasongrout**
Takes care of several issues that make using @interact painful, and upgrades labextension to a version that can use interact.

Demo (assuming you are using a dev install of ipywidgets master)
```python
from ipywidgets import interact, Output, HBox
left = Output()
right = Output()

with left:
    @interact(x=(0,10))
    def f(x):
        @interact(y=(0,x))
        def g(y):
            with right:
                print('Product',x*y)

print("Product calculator")                
HBox([left, right])
```

### CODE REVIEW

**Comment by jasongrout** [comment]
This is the last of my changes for our scipy talk. After we merge this, I'll cut a new release of jupyterlab.

**Comment by jasongrout** [comment]
CC @blink1073 - if you guys can review and merge this (I'd like some other eyes on it before it goes in), that would be great.

**Comment by blink1073** [comment]
Tested locally, looks great, thanks!

**Comment by jasongrout** [comment]
Awesome, thanks. I'll roll a 0.0.14 release.

**Pull request merged**
