### PR TITLE
Handle outputs during execution in the console

### LINKED ISSUE #936: Console doesn't show output until code is done running
```python
import time
for i in range(10):
    print(i)
    time.sleep(1)
```

This should show output as it comes back but only shows the output after everything has run.

### PR DESCRIPTION
**Pull request by blink1073**
Fixes #936.

### CODE REVIEW

**Comment by ellisonbg** [comment]
The behavior that I am seeing with this PR is that the console scrolls up only when a cell is finished running, but not if there is more output incrementally in the middle of running the cell. This shows the issue:

```python
import time
for i in range(50):
  print(i)
  time.sleep(1)
```

**Comment by blink1073** [comment]
That is the exact code I used to verify the PR locally...

**Comment by blink1073** [comment]
console-scroll

**Comment by afshin** [comment]
A clean build with this branch's code works for me.

**Comment by afshin** [comment]
👍

**Pull request merged**
