### PR TITLE
Use FocusTracker and onActivateRequest from phosphor

### LINKED ISSUE #635: Strange focus issue with stdin in the console: can't recover focus if lost
This is best illustrated with a gif, but the explanation is: stdin in the console works if one starts typing immediately, but if you move focus outside of the text box, it's impossible to recover the focus. Clicking again in the text area doesn't "hold" the focus, it jumps back out immediately.

console-stdin

### PR DESCRIPTION
**Pull request by blink1073**
cf #586.  Fixes #635.
Ensures there is only one "current widget" in the main area, with appropriate styling.  The old widget is explicitly deactivated when a new one gains focus.

Adds activate/deactivate handling to widgets added to the application that should take focus, and cleans up the handling of focus in the notebook.

focus-tracking

Stdin handling matches the behavior of the classic notebook:

stdin

Also fixes a bug where contexts were not being disposed properly.

### CODE REVIEW

**Comment by fperez** [comment]
thx, let me know if you need any testing here, happy to be the guinea pig.

**Comment by blink1073** [comment]
@fperez, this is ready for testing.  I still have to add explicit activate handling to some widgets, and add tests, but I like where the behavior is at for editors, notebooks, consoles, terminals, and images.

**Comment by blink1073** [comment]
Note that we don't *yet* have the ability to activate a widget by clicking on its tab, this is forthcoming in phosphor.

**Comment by blink1073** [comment]
I also plan to explicitly check your other issues.

**Comment by blink1073** [comment]
db01e58 fixes #635.

**Comment by fperez** [comment]
Tested interactively, confirming it fixes the behavior seen in #635.

And as suspected by @sccolbert and mentioned in the issue, I also confirm it fixes the re-occurrence of #355 (which we didn't reopen, so no action needed there).

Thanks!

**Comment by blink1073** [comment]
Thank you for the testing and feedback!

**Comment by afshin** [comment]
This is awesome, thanks!

👍

**Pull request merged**
