### PR TITLE
RenderMime updates and Markdown code highlighting

### PR DESCRIPTION
**Pull request by blink1073**
Moves the sanitization and trusted handling onto the RenderMime instance.
Also adds code highlighting, which prompted the need for an asynchronous render method.

cf https://github.com/jupyter/jupyterlab/issues/446#issuecomment-234672802
Fixes https://github.com/jupyter/jupyterlab/issues/131

screen shot 2016-07-25 at 11 15 56 am

### CODE REVIEW

**Comment by blink1073** [comment]
This is ready.

**Comment by blink1073** [comment]
Rebased and ready.

**Comment by afshin** [comment]
👍 

Awesome, thanks!

**Comment by jasongrout** [comment]
It looks like this really limits the sorts of outputs an IRender can produce (to HTMLElement or Widget). Somehow that got truncated even more in current master to just producing a Widget. I'll make a PR that adds back in the free type parameter for the render return type for IRender.

**Comment by jasongrout** [comment]
(was there a reason for limiting the IRender render return types to just HTMLElement and Widget?)

**Comment by jasongrout** [comment]
(cf. https://github.com/jupyter/jupyterlab/pull/538/files#diff-77b824ddb1758bbfa15d42208aa5432cR176)

**Comment by blink1073** [comment]
This was a vestige of when we temporarily had separate methods for transforming the raw data and rendering it.  Also, Darian and I had agreed that a widget is the "currency" of JupyterLab.  However, I am not opposed to making it generic again.

**Comment by jasongrout** [comment]
Ah. I had hoped it would be more general than just jupyterlab, if it isn't too much trouble now.

**Comment by jasongrout** [comment]
Hmmm...thinking to self: one big complication is that the tokens can't be parameterized, so if we had
```
const IRenderMime = new Token<IRenderMime<Widget>>('jupyter.services.rendermime');
interface IRenderMime<T> extends RenderMime<T> {}
```
when we import `IRenderMime`, we have to parameterize it when using it as a type, and have the assumed Widget type when using it as a token. That gets confusing. Even if we had
```
interface IRenderMime extends RenderMime<Widget> {}
```
that also gets confusing, since the interface is a specialization of the class. 

Not to mention now there is a ton of `<Widget>` parameterizations now littering the code (for options, etc.).

Maybe it's better to simplify at this point, and revisit making it more generic later if needed...

**Comment by blink1073** [comment]
We could have a generic class and interface and then export a `Widget`-reified set that we use everywhere in JLab itself.

**Pull request merged**
