### PR TITLE
Adopt the 3-clause BSD license template from opensource.org

### PR DESCRIPTION
**Pull request by jasongrout**
See the project discussion at https://groups.google.com/forum/#!topic/jupyter/vZpWgw8zKdc

Please do not merge this until the discussion has settled about the license wording.

### CODE REVIEW

**Comment by blink1073** [comment]
👍

**Comment by ellisonbg** [comment]
Status?

**Comment by blink1073** [comment]
I'd say merge if you concur, @ellisonbg.

**Comment by jasongrout** [comment]
@ellisonbg - Has the discussion settled? Do we want a legal opinion in addition to our own views? And I think (symbolically) either you or @fperez should be the one to merge this one.

**Comment by jasongrout** [comment]
(For the record, though, the three main contributors by far are all +1 in the comments above...)

**Comment by fperez** [comment]
I'm happy to merge it, and I'm +1 on the changes.  Even accepting a certain amount of legal ambiguity around the notion of "contributors" as a copyright holder, I think right now it's the best we have to communicate the more complex and nuanced mouthful of "everyone in the repo holds individual copyrights to their changes, and therefore the copyright of the whole repo is the sum total of those contributions, all of which are jointly licensed under the BSD terms..."

It's also somewhat accepted community-wide, so I think it's the best we're going to get for now.  We can't paralyze every step of our process until the Supreme Court gives us an opinion :)

**Comment by jasongrout** [comment]
@fperez - just waiting for you to hit the green button, then...

**Comment by ellisonbg** [comment]
I pinged the GG discussion for a decision on this issue as well...

**Comment by fperez** [comment]
Replied on list for a "last call" and to get this context in there too.  Will merge tomorrow if no significantly new concerns are raised.

**Comment by jasongrout** [comment]
I just want to note that the text for the third clause may read better if it was:

>  Neither the name of Project Jupyter nor the names of its
>  contributors may be used to endorse or promote products derived from
>  this software without specific prior written permission.

That seems to protect both the official project and the contributors (which are the copyright holders, as noted in the copyright statement). However, I'm also happy to defer to the OSI text, even if it seems a bit ambiguous in our case, especially if we have separate trademark protections for the Project Jupyter organization. I understand that there can be subtle ramifications of changing the license wording slightly, and can cause confusion even if there are multiple wordings of the license out there in common acceptance.

**Comment by fperez** [comment]
I'm going to merge it with the purely standard language: the less we customize, the easier it gets to communicate our licensing model.  For more detailed guidelines for endorsement/usage of the project names, logos, trademarks, etc, we'll have a proper policy elsewhere, just like the PSF and other projects.

Thanks everyone!!

**Pull request merged**
