### PR TITLE
Move the inspector to the main area and add a command to open it...

### PR DESCRIPTION
**Pull request by ellisonbg**
Talked about in person with @afshin and there was agreement that it is nice to be able to move it around.

### CODE REVIEW

**Comment by blink1073** [comment]
Should this command be auto-invoked on the `inspector.inspected` signal?

**Comment by ellisonbg** [comment]
Let's start with not auto invoking and see how it feels. Can add the auto invoking later.

**Comment by ellisonbg** [comment]
The `inspector.source` object

**Comment by ellisonbg** [comment]
The `inspector.source` object that has the `inspected` signal is added later so I can't watch that signal until the inspector is already working. Let's merge this as is and I will open an issue on this and ping @afshin

**Pull request merged**
