### PR TITLE
Issue 861: Small wording issue with JupyterLab preview

### PR DESCRIPTION
**Pull request by Deborah-Digges**
Fixes: https://github.com/jupyter/jupyterlab/issues/861

Preview:
screen shot 2016-09-28 at 8 30 08 pm

### CODE REVIEW

**Comment by blink1073** [comment]
Thanks!

**Comment by willingc** [comment]
Thanks @Deborah-Digges :smile: Nice to see you contributing over here. Hope all is well.

**Comment by Deborah-Digges** [comment]
Hi @willingc 😄 
Thank you! All is well - I'm resuming my contributions to open source and thought this would be a great project to contribute to. 
If there's anything in particular I can help out with, do let me know - I'd be really excited to help out 😄

**Comment by blink1073** [comment]
Thanks @Deborah-Digges!  All contributions are warmly welcomed.  Feel free to ping us on gitter if you have any questions.

**Pull request merged**
