### PR TITLE
Fix marked syntax highlighting and clean up the jupyter CodeMirror theme

### LINKED ISSUE #84: CodeMirror themes in JupyterLab not being processed correctly
screen shot 2016-06-15 at 5 11 22 pm

On the left is Jupyter Notebook, the color scheme is being inherited from the CodeMirror repo. JupyterLab's color scheme is just slightly different and that is a no-go. Brian says this has something to do with iPython/CodeMirror's themes not being processed correctly, but I'm not too sure.

### LINKED ISSUE #547: Bring forward the IPython highlighting theme
The existing theme is written in LESS, so either we add LESS to this repo or it needs to be translated to CSS:

https://github.com/jupyter/notebook/blob/41d6da235cbf3bcf6d7f818e11a066e0fd12ff8b/notebook/static/notebook/less/highlight.less

Would also need to update the `marked` options in this file https://github.com/jupyter/jupyterlab/blob/master/src/renderers/index.ts to match https://github.com/jupyter/notebook/blob/d8fc95173b489745b172cb86719cea855ea72acd/notebook/static/notebook/js/notebook.js#L88

### PR DESCRIPTION
**Pull request by ellisonbg**
This gets the marked syntax highlighting working with the classic notebook theme and ports that them over the JupyterLab in a way that is going to be more sustainable. The name of the theme is now `jupyter` to distinguish it from `default` which is the CM default.

From @blink1073:
Fixes #84.  Fixes #547.

### CODE REVIEW

**Comment by ellisonbg** [comment]
Here is a screenshot of showing syntax highlighting working in a code cell and markdown cell:

screen shot 2016-08-24 at 11 03 12 am

**Comment by blink1073** [comment]
This has a conflict.

**Comment by ellisonbg** [comment]
OK rebase pushed, but the tests were broken as well. All should be fixed, but let's wait on Travis.

**Comment by ellisonbg** [comment]
Hmm, why is the Travis status not showing on this one?

**Comment by blink1073** [comment]
When in doubt, shut off and on ;)

**Comment by blink1073** [comment]
:tada:

**Pull request merged**
