### PR TITLE
Make JQuery available globally

### PR DESCRIPTION
**Pull request by blink1073**
cc @charnpreetsingh185 @eskirk, this allows you to use `$()` in your code.

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
If the need for jquery is merely for basic DOM manipulation, we should be able to use native DOM APIs.

**Comment by afshin** [comment]
@SylvainCorlay jQuery is a dependency of the libs the new about page needs.

@blink1073 The before each test bandit strikes again.

**Comment by afshin** [comment]
👍

**Comment by jasongrout** [comment]
Jqueryui is still just needed for widgets though, right?

**Comment by jasongrout** [comment]
Jqueryui is still just needed for widgets, though, right?

**Comment by SylvainCorlay** [comment]
@jasongrout jqueryui would then be in the jupyter-js-widget bundle.

**Comment by blink1073** [comment]
For now, this ensures that jquery and jquery ui are not included *in* the webpack bundle.  I'm going to move codemirror out as well.

**Pull request merged**
