### PR TITLE
WIP Terminal Plugin Accessors

### PR DESCRIPTION
**Pull request by charnpreetsingh185**
I'm playing around with the TerminalWidget accessors for fontSize but whenever I console.log() the values I get an -1 for font size even though in the TerminalWidget object font size is 14. Why would this be happening? Also, trying to set the fontSize to 15 results in

 `Uncaught TypeError: Cannot read property 'element' of null`.

Attached console outputs and source line for the error.

screen shot 2016-06-30 at 4 57 44 pm
screen shot 2016-06-30 at 4 58 22 pm

### CODE REVIEW

**Comment by blink1073** [comment]
Ah, `this._term` is not set until the websocket to the server is opened, that is why setting font size before it is connected will not work.

**Comment by charnpreetsingh185** [comment]
ahh ok. That makes sense. So it shouldn't be a problem after `window.onload` is done executing, right?
Why is fontSize returning -1?

**Comment by blink1073** [comment]
The websocket open happens some (uncertain) time after onload.  You have found a bug, and I'll fix it tomorrow.

**Comment by blink1073** [comment]
Thanks for the report @charnpreetsingh185, this will be fixed once #206 is merged.

**Pull request closed without merging**
