### PR TITLE
Add 'preview' to the alpha warning on the landing page.

### PR DESCRIPTION
**Pull request by jasongrout**
CC @rnetro.

### CODE REVIEW

**Comment by blink1073** [comment]
It has been released on conda-forge and pypi as an alpha product, to me this is a misnomer and adds more confusion.

**Comment by groutr** [comment]
Does alpha imply a type of preview/prerelease?  The Jupyterlab talk, though, did specifically point out that it wasn't a release yet, but an early preview.

**Comment by jasongrout** [comment]
I was making the change to more clearly address people that didn't recognize "alpha" as meaning "prerelease". I read the text as "alpha prerelease <of the final product>", not "prerelease of an alpha" like Steve did. So now my thoughts are: 1. the product is targeted to people who know what "alpha" means at this stage, and the "This is not ready for general use" targets others., and 2. Clearly there is enough confusion from @blink1073 and @ayr0 about "alpha prerelease" that it defeats the purpose of being clearer. So I'll close this issue.

Thanks for your feedback!

**Comment by groutr** [comment]
@jasongrout I think the lack of clarity might lie with the term used.  After listening to the Jupyterlab talk again, "alpha preview" made sense to me.

**Comment by jasongrout** [comment]
@blink1073 - thoughts on "alpha preview"?

**Comment by blink1073** [comment]
Works for me, the recent debate over what "beta" means to the Tesla Autopilot demonstrates that it is better to be as explicit as possible.

**Comment by groutr** [comment]
"alpha preview" would also be consistent with the wording on the about tab in jupyter-plugins-demo.gif

**Comment by jasongrout** [comment]
All right, re-opening with the updated text, then.

**Comment by jasongrout** [comment]
Ready for review/merge, @blink1073

**Pull request merged**
