### PR TITLE
Send payload messages to output.

### PR DESCRIPTION
**Pull request by afshin**
Fixes https://github.com/jupyter/jupyterlab/issues/956

### CODE REVIEW

**Comment by afshin** [comment]
When this output is auto-saved, the server is not very happy:
```
Notebook JSON is invalid: {'data': {'text/plain': "\x1b[0;31mDocstring:\x1b[0m\nprint(value, ..., sep=' ', end='\\n', file=sys.stdout, flush=False)\n\nPrints the values to a stream, or to sys.stdout by default.\nOptional keyword arguments:\nfile:  a file-like object (stream); defaults to the current sys.stdout.\nsep:   string inserted between values, default a space.\nend:   string appended after the last value, default a newline.\nflush: whether to forcibly flush the stream.\n\x1b[0;31mType:\x1b[0m      builtin_function_or_method\n"}, 'output_type': 'execute_reply', 'execution_count': 1, 'metadata': {}} is not valid under any of the given schemas

    Failed validating 'oneOf' in schema['properties']['outputs']['items']:
        {'oneOf': [{'$ref': '#/definitions/execute_result'},
                   {'$ref': '#/definitions/display_data'},
                   {'$ref': '#/definitions/stream'},
                   {'$ref': '#/definitions/error'}],
         'type': 'object'}

    On instance['outputs'][0]:
        {'data': {'text/plain': '\x1b[0;31mDocstring:\x1b[0m\n'
                                "print(value, ..., sep=' ', end='\\n', "
                                'file=sys.stdout, flush=False)\n'
                                '\n'
                                'Prints the values to a stream, or to '
                                'sys.stdout by default.\n'
                                'Optional keyword arguments:\n'
                                'file:  a file-like object (stream); defaults '
                                'to the current sys.stdout.\n'
                                'sep:   string inserted between values, '
                                'default a space.\n'
                                'end:   string appended after the last value, '
                                'default a newline.\n'
                                'flush: whether to forcibly flush the stream.\n'
                                '\x1b[0;31mType:\x1b[0m      '
                                'builtin_function_or_method\n'},
         'execution_count': 1,
         'metadata': {},
         'output_type': 'execute_reply'}
```

**Comment by afshin** [comment]
Because `display_data` does not contain `execution_count`, the server is unhappy about that property's existence:

```
Notebook JSON is invalid: Additional properties are not allowed ('execution_count' was unexpected)

    Failed validating 'additionalProperties' in schema:
        {'additionalProperties': False,
         'description': 'Data displayed as a result of code cell execution.',
         'properties': {'data': {'$ref': '#/definitions/misc/mimebundle'},
                        'metadata': {'$ref': '#/definitions/misc/output_metadata'},
                        'output_type': {'description': 'Type of cell output.',
                                        'enum': ['display_data']}},
         'required': ['output_type', 'data', 'metadata'],
         'type': 'object'}

    On instance:
        {'data': {'text/plain': '\x1b[0;31mDocstring:\x1b[0m\n'
                                "print(value, ..., sep=' ', end='\\n', "
                                'file=sys.stdout, flush=False)\n'
                                '\n'
                                'Prints the values to a stream, or to '
                                'sys.stdout by default.\n'
                                'Optional keyword arguments:\n'
                                'file:  a file-like object (stream); defaults '
                                'to the current sys.stdout.\n'
                                'sep:   string inserted between values, '
                                'default a space.\n'
                                'end:   string appended after the last value, '
                                'default a newline.\n'
                                'flush: whether to forcibly flush the stream.\n'
                                '\x1b[0;31mType:\x1b[0m      '
                                'builtin_function_or_method\n'},
         'execution_count': 1,
         'metadata': {},
         'output_type': 'display_data'}
```

**Comment by afshin** [comment]
I don't know if my previous comment is grounds for stalling on this PR or going ahead. I'll defer to @blink1073 since he's more familiar with the back-end.

**Comment by blink1073** [comment]
There is no reason to associate an execution count with this data, I say remove the field.

**Comment by afshin** [comment]
Good call. Removed.

**Comment by blink1073** [comment]
Looks good, works as advertised, thanks!

**Pull request merged**
