### PR TITLE
Clean up the save handler

### LINKED ISSUE #760: Revert/overwrite dialog keeps popping up.
This may be a hard one to reproduce. I've had JLab open and running for a while, and I've messed around and edited a few new notebooks and text files. If I leave JLab alone for a while, eventually this dialog (see screenshot) will pop up, even though I don't have any stale tabs open. If I don't dismiss the dialog, a *new* identical one will keep popping up every few minutes. Eventually, I'll have dozens of dialogs to dismiss. After dismissing these using the "revert" option (in order to synchronize with disk), they continue to popup every few minutes.

capture

### LINKED ISSUE #786: Spurious "File changed" dialog appearing
This is a notebook that I'd just opened and had run a couple of cells into. No other browser tabs were open on JLab at all, and yet I got the "file changed" dialog:

image

I'd never seen this bug before, but it happened several times in a row today.  In this case, I'd had that notebook open for no more than 30 seconds.

There could be confusion regarding previous open files: while this notebook is brand new, in the same session I'd had another similarly titled ("Untitled.ipynb") open before.  But I had already shut it down and deleted the file, so this one should be completely clean.  It's possible that internally, Lab is still thinking the other one is open and is getting confused.

### PR DESCRIPTION
**Pull request by blink1073**
Fixes #760.  Fixes #786.

The save handler now disposes of itself when its context disposes, avoiding the error.

Also, it will not continue to raise dialogs when there is already one open.

I verified that the "file changed on disk" behavior itself works as intended by using `touch <filename>` in a terminal.

### CODE REVIEW

**Comment by blink1073** [comment]
I also verified the behavior of the dialog not showing up when already open, but showing up later if needed after being dismissed.

**Comment by jasongrout** [comment]
CC @sccolbert.

**Comment by sccolbert** [comment]
Looks reasonable to me.

**Comment by afshin** [comment]
👍

**Pull request merged**
